server:
  port: 8081

spring:
  application:
    name: msvc-students

  datasource:
    url: jdbc:mysql://localhost/students?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    server-url:
#      defaultZone: http://localhost:8761/eureka/
